language: node_js
sudo: false
node_js:
  - "6"
  - "8"

matrix:
  allow_failures:
  - node_js: "6"
  
cache:
  npm: false

install:
  - "npm install --ignore-scripts"
  - "npx allow-scripts"

jobs:
  include:
    - stage: release
      if: branch = master AND type = push
      node_js: "lts/*"
      deploy:
        provider: "script"
        skip_cleanup: true
        script:
          - "NPM_CONFIG_OTP=$(curl -s $NPM_OTP_URL) npx semantic-release"
