name: Node.js CI

on:
  push:

jobs:
  prepare-node-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: dominykas/test-things@master
        id: set-matrix
        with:
          gte: 10
          policy: lts

  test:

    needs: prepare-node-matrix

    strategy:
      matrix:
        node-version: ${{ fromJson(needs.prepare-node-matrix.outputs.matrix) }}
        operating-system: [ubuntu-latest, windows-latest, macos-latest]

    runs-on: ${{ matrix.operating-system }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
